import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { GraduationCap } from "lucide-react";
const CourseListItem = ({ id, title, summary, categories, image, careerType, pricing }) => {
    return (_jsxs("div", { className: "group w-full flex gap-4 p-4 border-b border-gray-200 hover:bg-gray-50/80 transition-all duration-300 cursor-pointer", onClick: () => {
            if (id && id !== undefined) {
                window.location.href = `/course/${id}`;
            }
            else {
                console.error('ID del curso no válido:', id);
            }
        }, children: [_jsx("div", { className: "relative w-24 sm:w-36 md:w-44 flex-shrink-0", children: _jsx("div", { className: "w-full p-1 bg-white shadow-sm", children: _jsx("div", { className: "relative w-full h-full overflow-hidden aspect-[4/3] sm:aspect-video", children: _jsx("img", { src: image || "/placeholder.svg", alt: title, className: "absolute inset-0 w-full h-full object-cover object-center transform transition-transform duration-300 group-hover:scale-105" }) }) }) }), _jsx("div", { className: "flex-grow min-w-0 flex flex-col justify-between py-1", children: _jsxs("div", { children: [_jsx("h3", { className: "text-base font-semibold text-gray-900 mb-1.5 line-clamp-2 group-hover:text-gray-700", children: title }), _jsx("p", { className: "text-sm text-gray-600 mb-2 line-clamp-2 sm:line-clamp-3", children: summary }), _jsxs("div", { className: "flex flex-wrap gap-1.5 mb-2", children: [_jsxs("span", { className: "inline-flex items-center gap-1 px-2 py-0.5 bg-slate-300 text-xs rounded-full", children: [_jsx(GraduationCap, { className: "w-3.5 h-3.5" }), careerType?.name || "Sin categoría"] }), _jsx("div", { className: "hidden sm:flex flex-wrap gap-1.5", children: categories.map((category, index) => (_jsx("span", { className: "inline-flex items-center px-2 py-0.5 bg-gray-100 text-gray-700 text-xs rounded-full", children: category.name }, index))) })] }), pricing && (_jsx("div", { className: "mt-2 flex items-center gap-2", children: pricing.finalPrice === 0 ? (_jsx("span", { className: "text-lg font-bold text-green-600", children: "Gratis" })) : pricing.hasDiscount ? (_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "text-lg font-bold text-green-600", children: ["$", pricing.finalPrice.toLocaleString()] }), _jsxs("span", { className: "text-sm text-gray-500 line-through", children: ["$", pricing.originalPrice.toLocaleString()] }), _jsxs("span", { className: "text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full font-medium", children: ["-", Math.round(((pricing.originalPrice - pricing.finalPrice) / pricing.originalPrice) * 100), "%"] })] })) : (_jsxs("span", { className: "text-lg font-bold text-gray-900", children: ["$", pricing.finalPrice.toLocaleString()] })) }))] }) })] }));
};
export default CourseListItem;
