import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatCurrency, formatDate } from "@/subscription/utils/formatDate";
export default function NextPayment({ subscription }) {
    const { mpSubscription, plan } = subscription;
    // Verificar si hay un descuento activo
    const hasActiveDiscount = plan.discountEvent?.isActive;
    // Calcular el precio con descuento si hay un descuento activo
    const amountToPay = hasActiveDiscount
        ? Number(plan.totalPrice) - (Number(plan.totalPrice) * plan.discountEvent.value) / 100
        : Number(plan.totalPrice);
    return (_jsxs("div", { className: "bg-white rounded-lg border border-[#eff6ff] shadow-sm", children: [_jsx("div", { className: "p-6 border-b border-[#eff6ff]", children: _jsx("h2", { className: "text-xl font-semibold text-[#0c154c]", children: "Pr\u00F3ximo Pago" }) }), _jsxs("div", { className: "p-6 space-y-4", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "bg-[#42d7c7] p-3 rounded-full", children: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-6 w-6 text-white", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("polyline", { points: "12 6 12 12 16 14" })] }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Fecha del pr\u00F3ximo pago" }), _jsx("p", { className: "font-medium text-[#0c154c]", children: formatDate(mpSubscription.nextPaymentDate) })] })] }), _jsxs("div", { className: "mt-4", children: [_jsx("p", { className: "text-sm text-gray-500", children: "Monto a debitar" }), hasActiveDiscount ? (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "text-xl font-bold text-[#0c154c]", children: formatCurrency(amountToPay) }), _jsx("span", { className: "text-sm line-through text-gray-500", children: formatCurrency(plan.totalPrice) }), _jsxs("span", { className: "bg-[#42d7c7] text-[#0c154c] text-xs font-medium px-2 py-1 rounded-full", children: [plan.discountEvent.value, "% OFF"] })] })) : (_jsx("p", { className: "text-xl font-bold text-[#0c154c]", children: formatCurrency(plan.totalPrice) })), hasActiveDiscount && plan.discountEvent?.description && (_jsx("p", { className: "text-sm text-[#1d4ed8] mt-1", children: plan.discountEvent.description }))] }), _jsx("div", { className: "mt-6 pt-4 border-t border-[#eff6ff]", children: _jsxs("div", { className: "flex items-center", children: [_jsx("img", { src: "/placeholder.svg?height=24&width=120", alt: "Mercado Pago", className: "h-6" }), _jsx("p", { className: "ml-2 text-sm text-gray-500", children: "Procesado por Mercado Pago" })] }) })] })] }));
}
